# web server
nginx:
  image: nginx:latest
  ports:
    - "8787:80"
  volumes:
    # app
    - ./app/src/discuz/x3.2:/usr/share/nginx/html
    # nginx configs
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
  links:
    - fpm:__DOCKER_PHP_FPM__

# php-fpm
fpm:
  build: ./php-fpm
  ports:
    - "9000"
  volumes:
    - ./app/src/discuz/x3.2:/usr/share/nginx/html:rw
    - ./php-fpm/work:/tmp/openrasp
    # Your php.ini
    - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
    - ./php-fpm/ext/openrasp.so:/tmp/openrasp.so:ro
    - ./php-fpm/conf.d/openrasp.ini:/usr/local/etc/php/conf.d/z_openrasp.ini:ro
  # environment:
    # Set your APP env variables here:
    # - APP_KEY=
    # - DB_HOST=
    # - DB_DATABASE=
    # - DB_USERNAME=
    # - DB_PASSWORD=
  links:
    - mysql:mysql

# database
mysql:
  image: mysql:5.6
  ports:
    # Allow client to access 3306
    - "8306:3306"
  volumes:
    # NOTE: your data will be stored in ./mysql
    - ./mysql/discuz/x3.2:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=openrasp
